name: Monitor Furnidata

on:
  schedule:
    - cron: '0 */4 * * *'  # Esegue ogni 4 ore (UTC)
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests deepdiff

      - name: Run furnidata monitor script
        working-directory: furnidata
        run: |
          python furnidata.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
