name: Monitor External Flash Texts

on:
  schedule:
    - cron: '0 */1 * * *'  # Esegue ogni 4 ore (UTC)
  workflow_dispatch:

jobs:
  monitor-external-flash-texts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests deepdiff

      - name: Run External Flash Texts Monitor
        working-directory: external_flash_texts
        run: |
          python external_flash_texts.py
        env:
          DISCORD_WEBHOOK_EXT_FLASH_TEXTS: ${{ secrets.DISCORD_WEBHOOK_EXT_FLASH_TEXTS }}
