name: Monitor External Flash Texts

on:
  schedule:
    - cron: '0 */1 * * *'  # Esegue ogni ora (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor-external-flash-texts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests deepdiff

      - name: Run External Flash Texts Monitor
        working-directory: external_flash_texts
        run: python external_flash_texts.py
        env:
          DISCORD_WEBHOOK_EXT_FLASH_TEXTS: ${{ secrets.DISCORD_WEBHOOK_EXT_FLASH_TEXTS }}

      - name: Commit and push External Flash Texts snapshot
        working-directory: external_flash_texts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git stash push -u
          git pull --rebase
          git stash pop || true
          git add external_flash_texts.txt
          git commit -m "Update External Flash Texts: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
