name: Aggiornamento Statistiche

on:
  schedule:
    - cron: '0 0 * * *'  # Esegue ogni giorno a mezzanotte (UTC)
  workflow_dispatch:   # Permette di eseguire il workflow manualmente

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: |
          python update_stats.py

      - name: Commit and push updated stats
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add historical_stats.json
          git commit -m "Aggiornamento statistiche: $(date +'%Y-%m-%d')" || echo "Nessun cambiamento"
          git push
